apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
      - name: nginx-cm-volume
        mountPath: "/usr/share/nginx/html" 
        readOnly: true
    ports:
      - containerPort: 80
  volumes:
    # You set volumes at the Pod level, then mount them into containers inside that Pod
    - name: nginx-cm-volume
      configMap:
        # Provide the name of the ConfigMap you want to mount.
        name: nginx-cm
        # An array of keys from the ConfigMap to create as files
        items:
        - key: "nginx.text"
          path: "index.html"